version = "0.3.X"

# Theme settings
defaultTheme = "auto"  # "light", "dark", or "auto"
disableThemeToggle = false

# Home page layout settings
[homeInfoParams]
Title = "Hi there 👋"
Content = """
hello! welcome to my rustic hugo site, set up in late 2024. 

i work in machine learning professionally, and enjoy learning about ML / tech, travel, food / cooking, mental health, and politics, among other related things. feel free to connect with me via social links below.
"""

# Social links
[[socialIcons]]
name = "email"
url = "mailto:wgrisaitis@gmail.com"

[[socialIcons]]
name = "whatsapp"
url = "https://wa.me/13214229231"

[[socialIcons]]
name = "github"
url = "https://github.com/grisaitis"

[[socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/grisaitis"

[[socialIcons]]
name = "twitter"
url = "https://twitter.com/grisaitis"

[[socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/grisaitis.bsky.social"

[[socialIcons]]
name = "goodreads"
url = "https://www.goodreads.com/user/show/3660834-william"

[page]
[page.math]
enable = true
blockLeftDelimiter = "\\["
blockRightDelimiter = "\\]"
inlineLeftDelimiter = "\\("
inlineRightDelimiter = "\\)"
copyTex = true
mhchem = true
